name: Weekly Radiology AI News Update

on:
  schedule:
    - cron: '0 12 * * 1'  # Runs at 8:00 AM ET every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run news aggregator
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
        LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
      run: python src/news_aggregator.py