name: Test Radiology AI News Bot

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug logging'
        required: false
        default: 'true'
      skip_posting:
        description: 'Skip LinkedIn posting'
        required: false
        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfontconfig1 libfreetype6
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create images directory
      run: mkdir -p images
    
    - name: Run test script
      env:
        LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
        LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        DEBUG_MODE: ${{ github.event.inputs.debug_mode }}
        SKIP_POSTING: ${{ github.event.inputs.skip_posting }}
      run: python src/test_bot.py